version: '3.8'

services:
  # Serviço da API (Backend)
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: real-it-api
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
      - /app/node_modules
    restart: always

  # Serviço do Web (Frontend)
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: real-it-web
    ports:
      - "3001:3000" # Acessível em localhost:3001 na sua máquina
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - api
    restart: always